name = "worker-aws"
main="index.js"
compatibility_date = "2022-05-03"

[build]
command = "npm run build"

[vars]
AWS_REGION = "us-east-1"
AWS_DYNAMO_TABLE = "test_table_name"
AWS_DYNAMO_PRIMARYKEY = "test_primary_key"
AWS_AURORA_TABLE = "demo.friends"
